version: 2.1

orbs:
  slack: circleci/slack@4.9.3

jobs:
  build:
    docker:
      - image: cimg/node:23.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: env
      - run: ls -alh
      - run: node --version
      #- run: npm install  # test,lint passしたら復活
      #- run: npm run test # test passしたら復活
      #- run: npm run lint # lint passしたら復活
      - slack/notify:
          event: always

workflows:
  notification:
    jobs:
      - build:
          context: ohr486-circleci-notification
