# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  slack: circleci/slack@4.9.3

jobs:
  build:
    docker:
      - image: cimg/node:23.11.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: node --version
      - run: env
      - run: ls -alh
      - run:
          name: Setting npm
          command: npm install
      - run:
          name: Run test
          command: npm run test
      - slack/notify:
          event: always

workflows:
  notification:
    jobs:
      - build:
        context: ohr486-circleci-notification
